version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "3002:3002"
      - "4200:4200"
    volumes:
      - ./frontend:/app/frontend
      - ./repo-interview-main:/app/repo-interview-main
      - /app/frontend/node_modules
      - /app/repo-interview-main/node_modules
